# Generated by Django 3.2 on 2023-06-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_unique_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-slug']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-slug']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-rating']},
        ),
    ]
