# Generated by Django 3.2 on 2023-06-09 05:23

from django.db import migrations, models
import reviews.validator


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230608_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.validator.year_validator], verbose_name='Год издания'),
        ),
    ]
