# Generated by Django 3.2 on 2023-06-09 06:16

from django.db import migrations, models
import reviews.validator


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(db_index=True, validators=[reviews.validator.year_validator], verbose_name='Год издания'),
        ),
    ]
